include_guard(GLOBAL)


function(ffmpegkit_dedupe_link_list INPUT_VAR)
    set(_out "")
    set(_seen "")

    foreach(_item IN LISTS ${INPUT_VAR})
        if("${_item}" STREQUAL "")
            continue()
        endif()

        if(EXISTS "${_item}")
            get_filename_component(_key "${_item}" REALPATH)
        else()
            set(_key "${_item}")
        endif()

        list(FIND _seen "${_key}" _found)
        if(_found EQUAL -1)
            list(APPEND _seen "${_key}")
            list(APPEND _out "${_item}")
        endif()
    endforeach()

    set(${INPUT_VAR} "${_out}" PARENT_SCOPE)
endfunction()

function(replace_static_with_shared INPUT_LIB OUTPUT_VAR)
    if(INPUT_LIB MATCHES "\\.a$" OR INPUT_LIB MATCHES "\\.lib$")
        if(WIN32)
            string(REPLACE ".a" ".dll" SHARED_PATH "${INPUT_LIB}")
        elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux" OR CMAKE_SYSTEM_NAME STREQUAL "Android")
            string(REPLACE ".a" ".so" SHARED_PATH "${INPUT_LIB}")
        elseif(APPLE)
            string(REPLACE ".a" ".dylib" SHARED_PATH "${INPUT_LIB}")
        else()
            set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
            return()
        endif()
        if(EXISTS "${SHARED_PATH}")
            set(${OUTPUT_VAR} "${SHARED_PATH}" PARENT_SCOPE)
            message(STATUS "Replaced ${INPUT_LIB} with ${SHARED_PATH}")
        else()
            message(STATUS "Shared library not found: ${SHARED_PATH}")
            set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
        endif()
    else()
        message(STATUS "Not a static library: ${INPUT_LIB}")
        set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
    endif()
endfunction()

function(get_pkg_config_static_library_dirs OUTPUT_VAR)
    set(_dirs "")

    if(NOT "$ENV{PKG_CONFIG_PATH}" STREQUAL "")
        set(_pkg_config_path "$ENV{PKG_CONFIG_PATH}")
        if(WIN32)
            string(REPLACE ";" "\\;" _pkg_config_path "${_pkg_config_path}")
        endif()
        string(REPLACE ":" ";" _pkg_config_entries "${_pkg_config_path}")

        foreach(_pc_dir IN LISTS _pkg_config_entries)
            if(_pc_dir STREQUAL "")
                continue()
            endif()

            file(TO_CMAKE_PATH "${_pc_dir}" _pc_dir)

            if(NOT IS_DIRECTORY "${_pc_dir}")
                continue()
            endif()

            list(APPEND _dirs "${_pc_dir}")

            get_filename_component(_pc_name "${_pc_dir}" NAME)
            get_filename_component(_pc_parent "${_pc_dir}" DIRECTORY)
            get_filename_component(_pc_parent_name "${_pc_parent}" NAME)
            get_filename_component(_pc_grandparent "${_pc_parent}" DIRECTORY)

            if(_pc_name STREQUAL "pkgconfig")
                if(_pc_parent_name STREQUAL "lib" OR _pc_parent_name STREQUAL "lib64")
                    list(APPEND _dirs "${_pc_parent}")
                elseif(_pc_parent_name STREQUAL "share")
                    list(APPEND _dirs "${_pc_grandparent}/lib")
                    list(APPEND _dirs "${_pc_grandparent}/lib64")
                else()
                    list(APPEND _dirs "${_pc_parent}/lib")
                    list(APPEND _dirs "${_pc_parent}/lib64")
                endif()
            endif()
        endforeach()
    endif()

    if(DEPENDENCY_BUILD_DIR)
        list(APPEND _dirs "${DEPENDENCY_BUILD_DIR}/lib")
        list(APPEND _dirs "${DEPENDENCY_BUILD_DIR}/lib64")
    endif()

    if(FFMPEG_BUILD_DIR)
        list(APPEND _dirs "${FFMPEG_BUILD_DIR}/lib")
        list(APPEND _dirs "${FFMPEG_BUILD_DIR}/lib64")
    endif()

    set(_existing_dirs "")
    foreach(_dir IN LISTS _dirs)
        if(IS_DIRECTORY "${_dir}")
            list(APPEND _existing_dirs "${_dir}")
        endif()
    endforeach()

    list(REMOVE_DUPLICATES _existing_dirs)
    set(${OUTPUT_VAR} "${_existing_dirs}" PARENT_SCOPE)
endfunction()

function(get_static_library_basename INPUT_LIB OUTPUT_VAR)
    set(_name "")

    if("${INPUT_LIB}" MATCHES "^-l(.+)$")
        set(_name "${CMAKE_MATCH_1}")
    else()
        get_filename_component(_file_name "${INPUT_LIB}" NAME)

        if(_file_name MATCHES "^lib(.+)\\.a$")
            set(_name "${CMAKE_MATCH_1}")
        elseif(_file_name MATCHES "^lib(.+)\\.dylib$")
            set(_name "${CMAKE_MATCH_1}")
        elseif(_file_name MATCHES "^lib(.+)\\.tbd$")
            set(_name "${CMAKE_MATCH_1}")
        elseif(_file_name MATCHES "^lib(.+)\\.so(\\..*)?$")
            set(_name "${CMAKE_MATCH_1}")
        elseif(_file_name MATCHES "^(.+)\\.dll$")
            set(_name "${CMAKE_MATCH_1}")
        endif()
    endif()

    if(_name MATCHES "^lib(.+)$")
        set(_name "${CMAKE_MATCH_1}")
    endif()

    string(REGEX REPLACE "(\\.[0-9]+)+$" "" _name "${_name}")
    set(${OUTPUT_VAR} "${_name}" PARENT_SCOPE)
endfunction()

function(find_static_library_in_pkg_config_path INPUT_LIB OUTPUT_VAR)
    set(_extra_search_dirs ${ARGN})
    get_static_library_basename("${INPUT_LIB}" _lib_name)

    if(NOT _lib_name)
        set(${OUTPUT_VAR} "" PARENT_SCOPE)
        return()
    endif()

    get_pkg_config_static_library_dirs(_static_search_dirs)
    if(_extra_search_dirs)
        list(PREPEND _static_search_dirs ${_extra_search_dirs})
    endif()
    list(REMOVE_DUPLICATES _static_search_dirs)

    if(NOT _static_search_dirs)
        set(${OUTPUT_VAR} "" PARENT_SCOPE)
        return()
    endif()

    foreach(_search_dir IN LISTS _static_search_dirs)
        if(NOT IS_DIRECTORY "${_search_dir}")
            continue()
        endif()

        set(_static_archive_path "${_search_dir}/lib${_lib_name}.a")
        if(EXISTS "${_static_archive_path}")
            set(${OUTPUT_VAR} "${_static_archive_path}" PARENT_SCOPE)
            return()
        endif()

        set(_static_archive_path "${_search_dir}/${_lib_name}.a")
        if(EXISTS "${_static_archive_path}")
            set(${OUTPUT_VAR} "${_static_archive_path}" PARENT_SCOPE)
            return()
        endif()
    endforeach()

    set(${OUTPUT_VAR} "" PARENT_SCOPE)
endfunction()

function(replace_shared_with_static INPUT_LIB OUTPUT_VAR)
    set(_extra_search_dirs ${ARGN})

    if(INPUT_LIB MATCHES "\\.a$" OR INPUT_LIB MATCHES "\\.lib$")
        set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
        return()
    endif()

    if(INPUT_LIB MATCHES "\\.dll\\.a$")
        string(REPLACE ".dll.a" ".a" STATIC_PATH "${INPUT_LIB}")
        if(EXISTS "${STATIC_PATH}")
            set(${OUTPUT_VAR} "${STATIC_PATH}" PARENT_SCOPE)
            message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_PATH}")
        else()
            find_static_library_in_pkg_config_path("${INPUT_LIB}" STATIC_FROM_PREFIX ${_extra_search_dirs})
            if(STATIC_FROM_PREFIX)
                set(${OUTPUT_VAR} "${STATIC_FROM_PREFIX}" PARENT_SCOPE)
                message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_FROM_PREFIX} from PKG_CONFIG_PATH")
            else()
                set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
            endif()
        endif()
        return()
    endif()

    if(INPUT_LIB MATCHES "\\.dll$")
        string(REPLACE ".dll" ".a" STATIC_PATH "${INPUT_LIB}")
        if(EXISTS "${STATIC_PATH}")
            set(${OUTPUT_VAR} "${STATIC_PATH}" PARENT_SCOPE)
            message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_PATH}")
        else()
            find_static_library_in_pkg_config_path("${INPUT_LIB}" STATIC_FROM_PREFIX ${_extra_search_dirs})
            if(STATIC_FROM_PREFIX)
                set(${OUTPUT_VAR} "${STATIC_FROM_PREFIX}" PARENT_SCOPE)
                message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_FROM_PREFIX} from PKG_CONFIG_PATH")
            else()
                set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
            endif()
        endif()
        return()
    endif()

    if(INPUT_LIB MATCHES "\\.so(\\.[0-9.]+)?$" OR INPUT_LIB MATCHES "\\.dylib$" OR INPUT_LIB MATCHES "\\.tbd$")
        find_static_library_in_pkg_config_path("${INPUT_LIB}" STATIC_FROM_PREFIX ${_extra_search_dirs})
        if(STATIC_FROM_PREFIX)
            set(${OUTPUT_VAR} "${STATIC_FROM_PREFIX}" PARENT_SCOPE)
            message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_FROM_PREFIX} from PKG_CONFIG_PATH")
            return()
        endif()

        if(INPUT_LIB MATCHES "\\.dylib$")
            string(REGEX REPLACE "(\\.[0-9]+)?\\.dylib$" ".a" STATIC_PATH "${INPUT_LIB}")
        elseif(INPUT_LIB MATCHES "\\.tbd$")
            string(REGEX REPLACE "\\.tbd$" ".a" STATIC_PATH "${INPUT_LIB}")
        else()
            string(REGEX REPLACE "\\.so(\\.[0-9.]+)?$" ".a" STATIC_PATH "${INPUT_LIB}")
        endif()

        if(EXISTS "${STATIC_PATH}")
            set(${OUTPUT_VAR} "${STATIC_PATH}" PARENT_SCOPE)
            message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_PATH}")
            return()
        endif()

        set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
        message(STATUS "No static replacement found for ${INPUT_LIB}; keeping original")
        return()
    endif()

    find_static_library_in_pkg_config_path("${INPUT_LIB}" STATIC_FROM_PREFIX ${_extra_search_dirs})
    if(STATIC_FROM_PREFIX)
        set(${OUTPUT_VAR} "${STATIC_FROM_PREFIX}" PARENT_SCOPE)
        message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_FROM_PREFIX} from PKG_CONFIG_PATH")
    else()
        set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
    endif()
endfunction()

function(replace_dll_a_with_dll INPUT_LIB OUTPUT_VAR)
    if(INPUT_LIB MATCHES "\\.dll\\.a$")
        string(REPLACE ".dll.a" ".dll" DLL_PATH "${INPUT_LIB}")
        if(EXISTS "${DLL_PATH}")
            set(${OUTPUT_VAR} "${DLL_PATH}" PARENT_SCOPE)
            message(STATUS "Replaced ${INPUT_LIB} with ${DLL_PATH}")
        else()
            string(REPLACE "/lib/" "/bin/" BIN_DLL_PATH "${DLL_PATH}")
            if(EXISTS "${BIN_DLL_PATH}")
                set(${OUTPUT_VAR} "${BIN_DLL_PATH}" PARENT_SCOPE)
                message(STATUS "Replaced ${INPUT_LIB} with ${BIN_DLL_PATH}")
            else()
                get_filename_component(LIB_DIR "${DLL_PATH}" DIRECTORY)
                get_filename_component(LIB_NAME "${DLL_PATH}" NAME_WE)
                if(LIB_NAME MATCHES "^lib")
                    string(REPLACE "lib" "" LIB_NAME_NO_LIB "${LIB_NAME}")
                else()
                    set(LIB_NAME_NO_LIB "${LIB_NAME}")
                endif()
                get_filename_component(PARENT_DIR "${LIB_DIR}" DIRECTORY)
                set(BIN_DLL_PATH_NO_LIB "${PARENT_DIR}/bin/${LIB_NAME_NO_LIB}.dll")
                if(EXISTS "${BIN_DLL_PATH_NO_LIB}")
                    set(${OUTPUT_VAR} "${BIN_DLL_PATH_NO_LIB}" PARENT_SCOPE)
                    message(STATUS "Replaced ${INPUT_LIB} with ${BIN_DLL_PATH_NO_LIB}")
                else()
                    set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
                endif()
            endif()
        endif()
    else()
        set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
    endif()
endfunction()

function(configure_static_linking LIBRARY_NAME STATIC_LINKING)
    get_target_property(${LIBRARY_NAME}_LIBS PkgConfig::${LIBRARY_NAME} INTERFACE_LINK_LIBRARIES)
    if(NOT ${LIBRARY_NAME}_LIBS OR ${LIBRARY_NAME}_LIBS MATCHES "-NOTFOUND$")
        set(${LIBRARY_NAME}_LIBS "${${LIBRARY_NAME}_LINK_LIBRARIES}")
    endif()
    message(DEBUG "configure_static_linking(${LIBRARY_NAME}): ${LIBRARY_NAME}_LIBRARY_DIRS = ${${LIBRARY_NAME}_LIBRARY_DIRS}")
    set(FIXED_LIBS "")
    foreach(LIB_PATH IN LISTS ${LIBRARY_NAME}_LIBS)
        if("${LIB_PATH}" MATCHES "^-framework")
            continue()
        endif()
        message(DEBUG "configure_static_linking(${LIBRARY_NAME}): checking entry '${LIB_PATH}'")
        if(LIB_PATH MATCHES "-NOTFOUND$" OR LIB_PATH STREQUAL "")
            message(WARNING "configure_static_linking(${LIBRARY_NAME}): skipping unresolved entry '${LIB_PATH}'")
            continue()
        else()
            if(NOT "${LIB_PATH}" MATCHES "\\.a$" AND NOT EXISTS "${LIB_PATH}")
                message(DEBUG "configure_static_linking(${LIBRARY_NAME}): ${LIB_PATH} file does not exist, searching for it")
                find_library(${LIB_PATH}_ABSOLUTE_PATH
                    NAMES ${LIB_PATH}
                    HINTS ${${LIBRARY_NAME}_LIBRARY_DIRS}
                    NO_DEFAULT_PATH
                    NO_CMAKE_FIND_ROOT_PATH
                )
                message(DEBUG "configure_static_linking(${LIBRARY_NAME}): ${LIB_PATH}_ABSOLUTE_PATH = ${${LIB_PATH}_ABSOLUTE_PATH}")
                if(NOT EXISTS "${${LIB_PATH}_ABSOLUTE_PATH}")
                    message(DEBUG "configure_static_linking(${LIBRARY_NAME}): ${${LIB_PATH}_ABSOLUTE_PATH} file does not exist after search")
                    continue()
                else()
                    message(STATUS "configure_static_linking(${LIBRARY_NAME}): replaced '${LIB_PATH}' with '${${LIB_PATH}_ABSOLUTE_PATH}'")
                    set(LIB_PATH "${${LIB_PATH}_ABSOLUTE_PATH}")
                endif()
            endif()
        endif()
        if(STATIC_LINKING)
            replace_shared_with_static("${LIB_PATH}" RESOLVED_LIB ${${LIBRARY_NAME}_LIBRARY_DIRS})
        else()
            if(MINGW)
                replace_dll_a_with_dll("${LIB_PATH}" RESOLVED_LIB)
            else()
                set(RESOLVED_LIB ${LIB_PATH})
            endif()
        endif()
        list(APPEND FIXED_LIBS "${RESOLVED_LIB}")
    endforeach()
    set_target_properties(PkgConfig::${LIBRARY_NAME} PROPERTIES INTERFACE_LINK_LIBRARIES "${FIXED_LIBS}")
    list(APPEND BUNDLE_LIBRARIES ${FIXED_LIBS})
    list(REMOVE_DUPLICATES BUNDLE_LIBRARIES)
    set(BUNDLE_LIBRARIES "${BUNDLE_LIBRARIES}" PARENT_SCOPE)
endfunction()

function(configure_shared_linking LIBRARY_NAME SHARED_LINKING)
    get_target_property(${LIBRARY_NAME}_LIBS PkgConfig::${LIBRARY_NAME} INTERFACE_LINK_LIBRARIES)
    if(NOT ${LIBRARY_NAME}_LIBS OR ${LIBRARY_NAME}_LIBS MATCHES "-NOTFOUND$")
        set(${LIBRARY_NAME}_LIBS "${${LIBRARY_NAME}_LINK_LIBRARIES}")
    endif()
    if(NOT ${LIBRARY_NAME}_LIBS_LIST)
        if(EXISTS "${${LIBRARY_NAME}_LIBRARY}")
            message(STATUS "configure_shared_linking(${LIBRARY_NAME}): ${LIBRARY_NAME} found at ${${LIBRARY_NAME}_LIBRARY}")
            set(${LIBRARY_NAME}_LIBS_LIST "${${LIBRARY_NAME}_LIBRARY}")
        elseif(EXISTS "${${LIBRARY_NAME}_LIBS}")
            message(STATUS "configure_shared_linking(${LIBRARY_NAME}): ${LIBRARY_NAME} found at ${${LIBRARY_NAME}_LIBS}")
            set(${LIBRARY_NAME}_LIBS_LIST "${${LIBRARY_NAME}_LIBS}")
        elseif(EXISTS "${${LIBRARY_NAME}_LIBRARIES}")
            message(STATUS "configure_shared_linking(${LIBRARY_NAME}): ${LIBRARY_NAME} found at ${${LIBRARY_NAME}_LIBRARIES}")
            set(${LIBRARY_NAME}_LIBS_LIST "${${LIBRARY_NAME}_LIBRARIES}")
        else()
            message(WARNING "configure_shared_linking(${LIBRARY_NAME}): ${LIBRARY_NAME}_LIBS_LIST is empty")
            return()
        endif()
    endif()
    set(FIXED_LIBS "")
    message(DEBUG "configure_shared_linking(${LIBRARY_NAME}): ${LIBRARY_NAME}_LIBS_LIST = ${${LIBRARY_NAME}_LIBS_LIST}")
    foreach(LIB_PATH IN LISTS ${LIBRARY_NAME}_LIBS_LIST)
        message(DEBUG "configure_shared_linking(${LIBRARY_NAME}): checking entry '${LIB_PATH}'")
        if(LIB_PATH MATCHES "-NOTFOUND$" OR LIB_PATH STREQUAL "")
            message(WARNING "configure_shared_linking(${LIBRARY_NAME}): skipping unresolved entry '${LIB_PATH}'")
            continue()
        endif()
        if(SHARED_LINKING)
            replace_static_with_shared("${LIB_PATH}" RESOLVED_LIB)
        else()
            if(MINGW)
                replace_dll_a_with_dll("${LIB_PATH}" RESOLVED_LIB)
            else()
                set(RESOLVED_LIB ${LIB_PATH})
            endif()
        endif()
        list(APPEND FIXED_LIBS "${RESOLVED_LIB}")
    endforeach()
    set_target_properties(PkgConfig::${LIBRARY_NAME} PROPERTIES INTERFACE_LINK_LIBRARIES "${FIXED_LIBS}")
    list(APPEND BUNDLE_LIBRARIES ${FIXED_LIBS})
    list(REMOVE_DUPLICATES BUNDLE_LIBRARIES)
    set(BUNDLE_LIBRARIES "${BUNDLE_LIBRARIES}" PARENT_SCOPE)
endfunction()
