include_guard(GLOBAL)


function(ffmpegkit_dedupe_link_list INPUT_VAR)
    set(_out "")
    set(_seen "")

    foreach(_item IN LISTS ${INPUT_VAR})
        if("${_item}" STREQUAL "")
            continue()
        endif()

        if(EXISTS "${_item}")
            get_filename_component(_key "${_item}" REALPATH)
        else()
            set(_key "${_item}")
        endif()

        list(FIND _seen "${_key}" _found)
        if(_found EQUAL -1)
            list(APPEND _seen "${_key}")
            list(APPEND _out "${_item}")
        endif()
    endforeach()

    set(${INPUT_VAR} "${_out}" PARENT_SCOPE)
endfunction()

function(resolve_project_static_library INPUT_LIB OUTPUT_VAR)
    set(_project_static_library "")

    if(EXISTS "${INPUT_LIB}")
        get_filename_component(_candidate_real "${INPUT_LIB}" REALPATH)
        if("${INPUT_LIB}" MATCHES "\\.a$" OR "${_candidate_real}" MATCHES "\\.a$")
            foreach(_prefix "${DEPENDENCY_BUILD_DIR}" "${FFMPEG_BUILD_DIR}")
                if(_prefix AND IS_DIRECTORY "${_prefix}")
                    get_filename_component(_prefix_real "${_prefix}" REALPATH)
                    string(FIND "${_candidate_real}/" "${_prefix_real}/" _prefix_index)
                    if(_prefix_index EQUAL 0)
                        set(_project_static_library "${_candidate_real}")
                        break()
                    endif()
                endif()
            endforeach()
        endif()
    endif()

    set(${OUTPUT_VAR} "${_project_static_library}" PARENT_SCOPE)
endfunction()

function(is_project_static_library INPUT_LIB OUTPUT_VAR)
    resolve_project_static_library("${INPUT_LIB}" _project_static_library)
    if(_project_static_library)
        set(_is_project_static ON)
    else()
        set(_is_project_static OFF)
    endif()

    set(${OUTPUT_VAR} "${_is_project_static}" PARENT_SCOPE)
endfunction()

function(replace_static_with_shared INPUT_LIB OUTPUT_VAR)
    if(INPUT_LIB MATCHES "\\.a$" OR INPUT_LIB MATCHES "\\.lib$")
        if(WIN32)
            string(REPLACE ".a" ".dll" SHARED_PATH "${INPUT_LIB}")
        elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux" OR CMAKE_SYSTEM_NAME STREQUAL "Android")
            string(REPLACE ".a" ".so" SHARED_PATH "${INPUT_LIB}")
        elseif(APPLE)
            string(REPLACE ".a" ".dylib" SHARED_PATH "${INPUT_LIB}")
        else()
            set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
            return()
        endif()
        if(EXISTS "${SHARED_PATH}")
            set(${OUTPUT_VAR} "${SHARED_PATH}" PARENT_SCOPE)
            message(STATUS "Replaced ${INPUT_LIB} with ${SHARED_PATH}")
        else()
            if(WIN32)
                string(REPLACE "/lib/" "/bin/" BIN_SHARED_PATH "${SHARED_PATH}")
                if(EXISTS "${BIN_SHARED_PATH}")
                    set(${OUTPUT_VAR} "${BIN_SHARED_PATH}" PARENT_SCOPE)
                    message(STATUS "Replaced ${INPUT_LIB} with ${BIN_SHARED_PATH}")
                    return()
                endif()
            endif()

            message(STATUS "Shared library not found: ${SHARED_PATH}")
            set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
        endif()
    else()
        message(STATUS "Not a static library: ${INPUT_LIB}")
        set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
    endif()
endfunction()

function(get_pkg_config_static_library_dirs OUTPUT_VAR)
    set(_dirs "")

    if(NOT "$ENV{PKG_CONFIG_PATH}" STREQUAL "")
        set(_pkg_config_path "$ENV{PKG_CONFIG_PATH}")
        if(WIN32)
            string(REPLACE ";" "\\;" _pkg_config_path "${_pkg_config_path}")
        endif()
        string(REPLACE ":" ";" _pkg_config_entries "${_pkg_config_path}")

        foreach(_pc_dir IN LISTS _pkg_config_entries)
            if(_pc_dir STREQUAL "")
                continue()
            endif()

            file(TO_CMAKE_PATH "${_pc_dir}" _pc_dir)

            if(NOT IS_DIRECTORY "${_pc_dir}")
                continue()
            endif()

            list(APPEND _dirs "${_pc_dir}")

            get_filename_component(_pc_name "${_pc_dir}" NAME)
            get_filename_component(_pc_parent "${_pc_dir}" DIRECTORY)
            get_filename_component(_pc_parent_name "${_pc_parent}" NAME)
            get_filename_component(_pc_grandparent "${_pc_parent}" DIRECTORY)

            if(_pc_name STREQUAL "pkgconfig")
                if(_pc_parent_name STREQUAL "lib" OR _pc_parent_name STREQUAL "lib64")
                    list(APPEND _dirs "${_pc_parent}")
                elseif(_pc_parent_name STREQUAL "share")
                    list(APPEND _dirs "${_pc_grandparent}/lib")
                    list(APPEND _dirs "${_pc_grandparent}/lib64")
                else()
                    list(APPEND _dirs "${_pc_parent}/lib")
                    list(APPEND _dirs "${_pc_parent}/lib64")
                endif()
            endif()
        endforeach()
    endif()

    if(DEPENDENCY_BUILD_DIR)
        list(APPEND _dirs "${DEPENDENCY_BUILD_DIR}/lib")
        list(APPEND _dirs "${DEPENDENCY_BUILD_DIR}/lib64")
    endif()

    if(FFMPEG_BUILD_DIR)
        list(APPEND _dirs "${FFMPEG_BUILD_DIR}/lib")
        list(APPEND _dirs "${FFMPEG_BUILD_DIR}/lib64")
    endif()

    set(_existing_dirs "")
    foreach(_dir IN LISTS _dirs)
        if(IS_DIRECTORY "${_dir}")
            list(APPEND _existing_dirs "${_dir}")
        endif()
    endforeach()

    list(REMOVE_DUPLICATES _existing_dirs)
    set(${OUTPUT_VAR} "${_existing_dirs}" PARENT_SCOPE)
endfunction()

function(get_static_library_basename INPUT_LIB OUTPUT_VAR)
    set(_name "")

    if("${INPUT_LIB}" MATCHES "^-l(.+)$")
        set(_name "${CMAKE_MATCH_1}")
    else()
        get_filename_component(_file_name "${INPUT_LIB}" NAME)

        if(_file_name MATCHES "^lib(.+)\\.dll\\.a$")
            set(_name "${CMAKE_MATCH_1}")
        elseif(_file_name MATCHES "^lib(.+)\\.a$")
            set(_name "${CMAKE_MATCH_1}")
        elseif(_file_name MATCHES "^lib(.+)\\.dylib$")
            set(_name "${CMAKE_MATCH_1}")
        elseif(_file_name MATCHES "^lib(.+)\\.tbd$")
            set(_name "${CMAKE_MATCH_1}")
        elseif(_file_name MATCHES "^lib(.+)\\.so(\\..*)?$")
            set(_name "${CMAKE_MATCH_1}")
        elseif(_file_name MATCHES "^(.+)\\.dll$")
            set(_name "${CMAKE_MATCH_1}")
        elseif(_file_name MATCHES "^[A-Za-z0-9_+.-]+$")
            set(_name "${_file_name}")
        endif()
    endif()

    if(_name MATCHES "^lib(.+)$")
        set(_name "${CMAKE_MATCH_1}")
    endif()

    string(REGEX REPLACE "(\\.[0-9]+)+$" "" _name "${_name}")
    set(${OUTPUT_VAR} "${_name}" PARENT_SCOPE)
endfunction()

function(ffmpegkit_link_resolution_cache_key CACHE_NAMESPACE INPUT_LIB OUTPUT_VAR)
    string(SHA256 _hash "${CACHE_NAMESPACE}|${INPUT_LIB}")
    set(${OUTPUT_VAR} "FFMPEGKIT_LINK_RESOLUTION_${_hash}" PARENT_SCOPE)
endfunction()

function(ffmpegkit_cache_link_resolution CACHE_NAMESPACE INPUT_LIB RESOLVED_LIB)
    if("${INPUT_LIB}" STREQUAL "" OR "${RESOLVED_LIB}" STREQUAL "")
        return()
    endif()

    ffmpegkit_link_resolution_cache_key("${CACHE_NAMESPACE}" "${INPUT_LIB}" _cache_key)
    set_property(GLOBAL PROPERTY "${_cache_key}" "${RESOLVED_LIB}")

    get_static_library_basename("${INPUT_LIB}" _input_name)
    if(_input_name AND NOT "${_input_name}" STREQUAL "${INPUT_LIB}")
        ffmpegkit_link_resolution_cache_key("${CACHE_NAMESPACE}" "${_input_name}" _basename_cache_key)
        set_property(GLOBAL PROPERTY "${_basename_cache_key}" "${RESOLVED_LIB}")
    endif()
endfunction()

function(ffmpegkit_bundle_library_matches_cache_namespace CACHE_NAMESPACE INPUT_LIB OUTPUT_VAR)
    set(_matched_lib "")
    get_static_library_basename("${INPUT_LIB}" _input_name)

    if(NOT _input_name)
        set(${OUTPUT_VAR} "" PARENT_SCOPE)
        return()
    endif()

    foreach(_bundle_lib IN LISTS BUNDLE_LIBRARIES)
        if(NOT EXISTS "${_bundle_lib}")
            continue()
        endif()

        get_static_library_basename("${_bundle_lib}" _bundle_name)
        if(NOT "${_bundle_name}" STREQUAL "${_input_name}")
            continue()
        endif()

        if(CACHE_NAMESPACE MATCHES "^STATIC_")
            if(NOT "${_bundle_lib}" MATCHES "\\.(a|lib)$")
                continue()
            endif()
        elseif(CACHE_NAMESPACE MATCHES "^SHARED_ON$")
            if(NOT "${_bundle_lib}" MATCHES "\\.(so(\\..*)?|dylib|dll|tbd)$")
                continue()
            endif()
        endif()

        get_filename_component(_matched_lib "${_bundle_lib}" REALPATH)
        break()
    endforeach()

    set(${OUTPUT_VAR} "${_matched_lib}" PARENT_SCOPE)
endfunction()

function(ffmpegkit_get_cached_link_resolution CACHE_NAMESPACE INPUT_LIB OUTPUT_VAR FOUND_VAR)
    ffmpegkit_link_resolution_cache_key("${CACHE_NAMESPACE}" "${INPUT_LIB}" _cache_key)
    get_property(_has_cached_value GLOBAL PROPERTY "${_cache_key}" SET)
    if(_has_cached_value)
        get_property(_cached_value GLOBAL PROPERTY "${_cache_key}")
        set(${OUTPUT_VAR} "${_cached_value}" PARENT_SCOPE)
        set(${FOUND_VAR} TRUE PARENT_SCOPE)
        return()
    endif()

    get_static_library_basename("${INPUT_LIB}" _input_name)
    if(_input_name AND NOT "${_input_name}" STREQUAL "${INPUT_LIB}")
        ffmpegkit_link_resolution_cache_key("${CACHE_NAMESPACE}" "${_input_name}" _basename_cache_key)
        get_property(_has_cached_value GLOBAL PROPERTY "${_basename_cache_key}" SET)
        if(_has_cached_value)
            get_property(_cached_value GLOBAL PROPERTY "${_basename_cache_key}")
            ffmpegkit_cache_link_resolution("${CACHE_NAMESPACE}" "${INPUT_LIB}" "${_cached_value}")
            set(${OUTPUT_VAR} "${_cached_value}" PARENT_SCOPE)
            set(${FOUND_VAR} TRUE PARENT_SCOPE)
            return()
        endif()
    endif()

    ffmpegkit_bundle_library_matches_cache_namespace("${CACHE_NAMESPACE}" "${INPUT_LIB}" _bundle_match)
    if(_bundle_match)
        ffmpegkit_cache_link_resolution("${CACHE_NAMESPACE}" "${INPUT_LIB}" "${_bundle_match}")
        set(${OUTPUT_VAR} "${_bundle_match}" PARENT_SCOPE)
        set(${FOUND_VAR} TRUE PARENT_SCOPE)
        return()
    endif()

    set(${OUTPUT_VAR} "" PARENT_SCOPE)
    set(${FOUND_VAR} FALSE PARENT_SCOPE)
endfunction()

function(ffmpegkit_configure_android_static_cxx_runtime TARGET_NAME OUT_CXX_STATIC_LIBRARY OUT_CXXABI_STATIC_LIBRARY)
    if(NOT ANDROID)
        set(${OUT_CXX_STATIC_LIBRARY} "" PARENT_SCOPE)
        set(${OUT_CXXABI_STATIC_LIBRARY} "" PARENT_SCOPE)
        return()
    endif()

    target_link_options(${TARGET_NAME} PRIVATE "-nostdlib++")

    set(_android_cxx_runtime_abi "${CMAKE_ANDROID_ARCH_ABI}")
    if(NOT _android_cxx_runtime_abi)
        set(_android_cxx_runtime_abi "${ANDROID_ABI}")
    endif()

    if(_android_cxx_runtime_abi STREQUAL "arm64-v8a")
        set(_android_cxx_runtime_triple "aarch64-linux-android")
    elseif(_android_cxx_runtime_abi STREQUAL "armeabi-v7a")
        set(_android_cxx_runtime_triple "arm-linux-androideabi")
    elseif(_android_cxx_runtime_abi STREQUAL "x86")
        set(_android_cxx_runtime_triple "i686-linux-android")
    elseif(_android_cxx_runtime_abi STREQUAL "x86_64")
        set(_android_cxx_runtime_triple "x86_64-linux-android")
    else()
        message(FATAL_ERROR "Unsupported Android ABI for static libc++ lookup: ${_android_cxx_runtime_abi}")
    endif()

    find_library(_android_cxx_static_library
        NAMES libc++_static.a c++_static
        PATHS "${CMAKE_SYSROOT}/usr/lib/${_android_cxx_runtime_triple}"
        NO_DEFAULT_PATH
    )
    find_library(_android_cxxabi_static_library
        NAMES libc++abi.a c++abi
        PATHS "${CMAKE_SYSROOT}/usr/lib/${_android_cxx_runtime_triple}"
        NO_DEFAULT_PATH
    )

    if(EXISTS "${_android_cxx_static_library}")
        get_filename_component(_android_cxx_static_library "${_android_cxx_static_library}" REALPATH)
    else()
        message(FATAL_ERROR "Android static libc++ not found in ${CMAKE_SYSROOT}/usr/lib/${_android_cxx_runtime_triple}")
    endif()

    if(EXISTS "${_android_cxxabi_static_library}")
        get_filename_component(_android_cxxabi_static_library "${_android_cxxabi_static_library}" REALPATH)
    else()
        message(FATAL_ERROR "Android static libc++abi not found in ${CMAKE_SYSROOT}/usr/lib/${_android_cxx_runtime_triple}")
    endif()

    set(${OUT_CXX_STATIC_LIBRARY} "${_android_cxx_static_library}" PARENT_SCOPE)
    set(${OUT_CXXABI_STATIC_LIBRARY} "${_android_cxxabi_static_library}" PARENT_SCOPE)
endfunction()

function(ffmpegkit_filter_android_bundle_libraries INPUT_VAR OUTPUT_VAR)
    set(_filtered_libraries "")

    foreach(_bundle_lib IN LISTS ${INPUT_VAR})
        if("${_bundle_lib}" MATCHES "^-lc\\+\\+(_shared|_static)?$"
            OR "${_bundle_lib}" MATCHES "^-lstdc\\+\\+$"
            OR "${_bundle_lib}" MATCHES "^-lc\\+\\+abi$")
            message(STATUS "Removed Android dynamic/default C++ runtime link entry: ${_bundle_lib}")
            continue()
        endif()

        get_filename_component(_bundle_lib_name "${_bundle_lib}" NAME)
        if(EXISTS "${_bundle_lib}" AND _bundle_lib_name MATCHES "^(.+)\\.so(\\..*)?$")
            get_filename_component(_bundle_lib_dir "${_bundle_lib}" DIRECTORY)
            set(_bundle_static_candidate "${_bundle_lib_dir}/${CMAKE_MATCH_1}.a")
            list(FIND ${INPUT_VAR} "${_bundle_static_candidate}" _bundle_static_index)
            if(EXISTS "${_bundle_static_candidate}" OR NOT _bundle_static_index EQUAL -1)
                message(STATUS "Removed Android shared library with static counterpart: ${_bundle_lib}")
                continue()
            endif()
        endif()

        if(_bundle_lib_name MATCHES "^libc\\+\\+(_shared|_static)?\\.(so|a)$"
            OR _bundle_lib_name MATCHES "^libstdc\\+\\+\\.so$"
            OR _bundle_lib_name MATCHES "^libc\\+\\+abi\\.a$")
            message(STATUS "Removed Android dynamic/default C++ runtime link entry: ${_bundle_lib}")
            continue()
        endif()

        list(APPEND _filtered_libraries "${_bundle_lib}")
    endforeach()

    set(${OUTPUT_VAR} "${_filtered_libraries}" PARENT_SCOPE)
endfunction()

function(find_static_library_in_dir SEARCH_DIR LIB_NAME OUTPUT_VAR)
    if(NOT IS_DIRECTORY "${SEARCH_DIR}")
        set(${OUTPUT_VAR} "" PARENT_SCOPE)
        return()
    endif()

    set(_static_archive_path "${SEARCH_DIR}/lib${LIB_NAME}.a")
    if(EXISTS "${_static_archive_path}")
        set(${OUTPUT_VAR} "${_static_archive_path}" PARENT_SCOPE)
        return()
    endif()

    set(_static_archive_path "${SEARCH_DIR}/${LIB_NAME}.a")
    if(EXISTS "${_static_archive_path}")
        set(${OUTPUT_VAR} "${_static_archive_path}" PARENT_SCOPE)
        return()
    endif()

    file(GLOB_RECURSE _nested_candidates
        LIST_DIRECTORIES false
        "${SEARCH_DIR}/*/lib${LIB_NAME}.a"
        "${SEARCH_DIR}/*/${LIB_NAME}.a"
    )
    list(SORT _nested_candidates)
    list(LENGTH _nested_candidates _nested_candidate_count)
    if(_nested_candidate_count GREATER 0)
        list(GET _nested_candidates 0 _first_nested_candidate)
        set(${OUTPUT_VAR} "${_first_nested_candidate}" PARENT_SCOPE)
        return()
    endif()

    set(${OUTPUT_VAR} "" PARENT_SCOPE)
endfunction()

function(find_static_library_in_pkg_config_path INPUT_LIB OUTPUT_VAR)
    set(_extra_search_dirs ${ARGN})
    get_static_library_basename("${INPUT_LIB}" _lib_name)

    if(NOT _lib_name)
        set(${OUTPUT_VAR} "" PARENT_SCOPE)
        return()
    endif()

    get_pkg_config_static_library_dirs(_static_search_dirs)
    if(_extra_search_dirs)
        list(PREPEND _static_search_dirs ${_extra_search_dirs})
    endif()
    list(REMOVE_DUPLICATES _static_search_dirs)

    if(NOT _static_search_dirs)
        set(${OUTPUT_VAR} "" PARENT_SCOPE)
        return()
    endif()

    foreach(_search_dir IN LISTS _static_search_dirs)
        if(NOT IS_DIRECTORY "${_search_dir}")
            continue()
        endif()

        find_static_library_in_dir("${_search_dir}" "${_lib_name}" _static_archive_path)
        if(_static_archive_path)
            set(${OUTPUT_VAR} "${_static_archive_path}" PARENT_SCOPE)
            return()
        endif()
    endforeach()

    set(${OUTPUT_VAR} "" PARENT_SCOPE)
endfunction()

function(find_project_static_library_for_link INPUT_LIB OUTPUT_VAR)
    set(_extra_search_dirs ${ARGN})
    set(_project_search_dirs "")

    foreach(_prefix "${DEPENDENCY_BUILD_DIR}" "${FFMPEG_BUILD_DIR}")
        if(_prefix AND IS_DIRECTORY "${_prefix}")
            list(APPEND _project_search_dirs "${_prefix}/lib" "${_prefix}/lib64")
        endif()
    endforeach()

    foreach(_dir IN LISTS _extra_search_dirs)
        if(IS_DIRECTORY "${_dir}")
            get_filename_component(_dir_real "${_dir}" REALPATH)
            foreach(_prefix "${DEPENDENCY_BUILD_DIR}" "${FFMPEG_BUILD_DIR}")
                if(_prefix AND IS_DIRECTORY "${_prefix}")
                    get_filename_component(_prefix_real "${_prefix}" REALPATH)
                    string(FIND "${_dir_real}/" "${_prefix_real}/" _prefix_index)
                    if(_prefix_index EQUAL 0)
                        list(APPEND _project_search_dirs "${_dir}")
                    endif()
                endif()
            endforeach()
        endif()
    endforeach()

    list(REMOVE_DUPLICATES _project_search_dirs)
    find_static_library_in_pkg_config_path("${INPUT_LIB}" _static_from_project ${_project_search_dirs})
    resolve_project_static_library("${_static_from_project}" _resolved_static_from_project)
    if(_resolved_static_from_project)
        set(${OUTPUT_VAR} "${_resolved_static_from_project}" PARENT_SCOPE)
    else()
        set(${OUTPUT_VAR} "" PARENT_SCOPE)
    endif()
endfunction()

function(replace_shared_with_static INPUT_LIB OUTPUT_VAR)
    set(_extra_search_dirs ${ARGN})

    if(INPUT_LIB MATCHES "\\.a$" OR INPUT_LIB MATCHES "\\.lib$")
        set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
        return()
    endif()

    if(INPUT_LIB MATCHES "\\.dll\\.a$")
        string(REPLACE ".dll.a" ".a" STATIC_PATH "${INPUT_LIB}")
        resolve_project_static_library("${STATIC_PATH}" STATIC_PATH_IN_PROJECT_PREFIX)
        if(STATIC_PATH_IN_PROJECT_PREFIX)
            set(${OUTPUT_VAR} "${STATIC_PATH_IN_PROJECT_PREFIX}" PARENT_SCOPE)
            message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_PATH_IN_PROJECT_PREFIX}")
        else()
            find_project_static_library_for_link("${INPUT_LIB}" STATIC_FROM_PREFIX ${_extra_search_dirs})
            if(STATIC_FROM_PREFIX)
                set(${OUTPUT_VAR} "${STATIC_FROM_PREFIX}" PARENT_SCOPE)
                message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_FROM_PREFIX} from PKG_CONFIG_PATH")
            else()
                set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
            endif()
        endif()
        return()
    endif()

    if(INPUT_LIB MATCHES "\\.dll$")
        string(REPLACE ".dll" ".a" STATIC_PATH "${INPUT_LIB}")
        resolve_project_static_library("${STATIC_PATH}" STATIC_PATH_IN_PROJECT_PREFIX)
        if(STATIC_PATH_IN_PROJECT_PREFIX)
            set(${OUTPUT_VAR} "${STATIC_PATH_IN_PROJECT_PREFIX}" PARENT_SCOPE)
            message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_PATH_IN_PROJECT_PREFIX}")
        else()
            find_project_static_library_for_link("${INPUT_LIB}" STATIC_FROM_PREFIX ${_extra_search_dirs})
            if(STATIC_FROM_PREFIX)
                set(${OUTPUT_VAR} "${STATIC_FROM_PREFIX}" PARENT_SCOPE)
                message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_FROM_PREFIX} from PKG_CONFIG_PATH")
            else()
                set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
            endif()
        endif()
        return()
    endif()

    if(INPUT_LIB MATCHES "\\.so(\\.[0-9.]+)?$" OR INPUT_LIB MATCHES "\\.dylib$" OR INPUT_LIB MATCHES "\\.tbd$")
        resolve_project_static_library("${INPUT_LIB}" STATIC_SYMLINK_TARGET)
        if(STATIC_SYMLINK_TARGET)
            set(${OUTPUT_VAR} "${STATIC_SYMLINK_TARGET}" PARENT_SCOPE)
            message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_SYMLINK_TARGET} from symlink target")
            return()
        endif()

        if(INPUT_LIB MATCHES "\\.dylib$")
            string(REGEX REPLACE "(\\.[0-9]+)?\\.dylib$" ".a" STATIC_PATH "${INPUT_LIB}")
        elseif(INPUT_LIB MATCHES "\\.tbd$")
            string(REGEX REPLACE "\\.tbd$" ".a" STATIC_PATH "${INPUT_LIB}")
        else()
            string(REGEX REPLACE "\\.so(\\.[0-9.]+)?$" ".a" STATIC_PATH "${INPUT_LIB}")
        endif()

        resolve_project_static_library("${STATIC_PATH}" STATIC_PATH_IN_PROJECT_PREFIX)
        if(STATIC_PATH_IN_PROJECT_PREFIX)
            set(${OUTPUT_VAR} "${STATIC_PATH_IN_PROJECT_PREFIX}" PARENT_SCOPE)
            message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_PATH_IN_PROJECT_PREFIX}")
            return()
        endif()

        if(EXISTS "${INPUT_LIB}")
            get_filename_component(_input_lib_dir "${INPUT_LIB}" DIRECTORY)
            find_project_static_library_for_link("${INPUT_LIB}" STATIC_FROM_SAME_DIR "${_input_lib_dir}")
            if(STATIC_FROM_SAME_DIR)
                set(${OUTPUT_VAR} "${STATIC_FROM_SAME_DIR}" PARENT_SCOPE)
                message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_FROM_SAME_DIR} from same library directory")
                return()
            endif()
        endif()

        find_project_static_library_for_link("${INPUT_LIB}" STATIC_FROM_PREFIX ${_extra_search_dirs})
        if(STATIC_FROM_PREFIX)
            set(${OUTPUT_VAR} "${STATIC_FROM_PREFIX}" PARENT_SCOPE)
            message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_FROM_PREFIX} from PKG_CONFIG_PATH")
            return()
        endif()

        set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
        message(STATUS "No static replacement found for ${INPUT_LIB}; keeping original")
        return()
    endif()

    find_project_static_library_for_link("${INPUT_LIB}" STATIC_FROM_PREFIX ${_extra_search_dirs})
    if(STATIC_FROM_PREFIX)
        set(${OUTPUT_VAR} "${STATIC_FROM_PREFIX}" PARENT_SCOPE)
        message(STATUS "Replaced ${INPUT_LIB} with ${STATIC_FROM_PREFIX} from PKG_CONFIG_PATH")
    else()
        set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
    endif()
endfunction()

function(resolve_mingw_static_runtime_library INPUT_LIB OUTPUT_VAR)
    set(_static_runtime_library "")

    if(MINGW)
        get_static_library_basename("${INPUT_LIB}" _lib_name)
        if(_lib_name MATCHES "^(ssp)$" OR _lib_name MATCHES "^(stdc\\+\\+)$")
            execute_process(
                COMMAND "${CMAKE_CXX_COMPILER}" "-print-file-name=lib${_lib_name}.a"
                OUTPUT_VARIABLE _candidate_static_runtime_library
                OUTPUT_STRIP_TRAILING_WHITESPACE
            )
            if(EXISTS "${_candidate_static_runtime_library}")
                set(_static_runtime_library "${_candidate_static_runtime_library}")
            endif()
        endif()
    endif()

    set(${OUTPUT_VAR} "${_static_runtime_library}" PARENT_SCOPE)
endfunction()

function(replace_mingw_runtime_imports_with_static INPUT_VAR)
    set(_fixed_libs "")

    foreach(_lib IN LISTS ${INPUT_VAR})
        resolve_mingw_static_runtime_library("${_lib}" _static_runtime_library)
        if(_static_runtime_library)
            message(STATUS "Replaced MinGW runtime import ${_lib} with ${_static_runtime_library}")
            list(APPEND _fixed_libs "${_static_runtime_library}")
        else()
            list(APPEND _fixed_libs "${_lib}")
        endif()
    endforeach()

    ffmpegkit_dedupe_link_list(_fixed_libs)
    set(${INPUT_VAR} "${_fixed_libs}" PARENT_SCOPE)
endfunction()

function(replace_dll_a_with_dll INPUT_LIB OUTPUT_VAR)
    if(INPUT_LIB MATCHES "\\.dll\\.a$")
        string(REPLACE ".dll.a" ".dll" DLL_PATH "${INPUT_LIB}")
        if(EXISTS "${DLL_PATH}")
            set(${OUTPUT_VAR} "${DLL_PATH}" PARENT_SCOPE)
            message(STATUS "Replaced ${INPUT_LIB} with ${DLL_PATH}")
        else()
            string(REPLACE "/lib/" "/bin/" BIN_DLL_PATH "${DLL_PATH}")
            if(EXISTS "${BIN_DLL_PATH}")
                set(${OUTPUT_VAR} "${BIN_DLL_PATH}" PARENT_SCOPE)
                message(STATUS "Replaced ${INPUT_LIB} with ${BIN_DLL_PATH}")
            else()
                get_filename_component(LIB_DIR "${DLL_PATH}" DIRECTORY)
                get_filename_component(LIB_NAME "${DLL_PATH}" NAME_WE)
                if(LIB_NAME MATCHES "^lib")
                    string(REPLACE "lib" "" LIB_NAME_NO_LIB "${LIB_NAME}")
                else()
                    set(LIB_NAME_NO_LIB "${LIB_NAME}")
                endif()
                get_filename_component(PARENT_DIR "${LIB_DIR}" DIRECTORY)
                set(BIN_DLL_PATH_NO_LIB "${PARENT_DIR}/bin/${LIB_NAME_NO_LIB}.dll")
                if(EXISTS "${BIN_DLL_PATH_NO_LIB}")
                    set(${OUTPUT_VAR} "${BIN_DLL_PATH_NO_LIB}" PARENT_SCOPE)
                    message(STATUS "Replaced ${INPUT_LIB} with ${BIN_DLL_PATH_NO_LIB}")
                else()
                    set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
                endif()
            endif()
        endif()
    else()
        set(${OUTPUT_VAR} "${INPUT_LIB}" PARENT_SCOPE)
    endif()
endfunction()

function(configure_static_linking LIBRARY_NAME STATIC_LINKING)
    get_target_property(${LIBRARY_NAME}_LIBS PkgConfig::${LIBRARY_NAME} INTERFACE_LINK_LIBRARIES)
    if(NOT ${LIBRARY_NAME}_LIBS OR ${LIBRARY_NAME}_LIBS MATCHES "-NOTFOUND$")
        set(${LIBRARY_NAME}_LIBS "${${LIBRARY_NAME}_LINK_LIBRARIES}")
    endif()
    message(DEBUG "configure_static_linking(${LIBRARY_NAME}): ${LIBRARY_NAME}_LIBRARY_DIRS = ${${LIBRARY_NAME}_LIBRARY_DIRS}")
    set(${LIBRARY_NAME}_REAL_LIBRARY_DIRS "")
    foreach(LIBRARY_DIR IN LISTS ${LIBRARY_NAME}_LIBRARY_DIRS)
        if(EXISTS "${LIBRARY_DIR}")
            get_filename_component(LIBRARY_DIR_REALPATH "${LIBRARY_DIR}" REALPATH)
            list(APPEND ${LIBRARY_NAME}_REAL_LIBRARY_DIRS "${LIBRARY_DIR_REALPATH}")
        else()
            list(APPEND ${LIBRARY_NAME}_REAL_LIBRARY_DIRS "${LIBRARY_DIR}")
        endif()
    endforeach()
    set(FIXED_LIBS "")
    set(_cache_namespace "STATIC_${STATIC_LINKING}")
    foreach(LIB_PATH IN LISTS ${LIBRARY_NAME}_LIBS)
        if("${LIB_PATH}" MATCHES "^-framework")
            continue()
        endif()
        message(DEBUG "configure_static_linking(${LIBRARY_NAME}): checking entry '${LIB_PATH}'")
        if(LIB_PATH MATCHES "-NOTFOUND$" OR LIB_PATH STREQUAL "")
            message(WARNING "configure_static_linking(${LIBRARY_NAME}): skipping unresolved entry '${LIB_PATH}'")
            continue()
        else()
            set(_original_lib_path "${LIB_PATH}")
            ffmpegkit_get_cached_link_resolution("${_cache_namespace}" "${_original_lib_path}" RESOLVED_LIB _cache_hit)
            if(_cache_hit)
                message(DEBUG "configure_static_linking(${LIBRARY_NAME}): cache hit '${_original_lib_path}' -> '${RESOLVED_LIB}'")
                list(APPEND FIXED_LIBS "${RESOLVED_LIB}")
                continue()
            endif()
            if(NOT "${LIB_PATH}" MATCHES "\\.a$" AND NOT EXISTS "${LIB_PATH}")
                message(DEBUG "configure_static_linking(${LIBRARY_NAME}): ${LIB_PATH} file does not exist, searching for it")
                find_library(${LIB_PATH}_ABSOLUTE_PATH
                    NAMES ${LIB_PATH}
                    HINTS ${${LIBRARY_NAME}_REAL_LIBRARY_DIRS}
                    NO_DEFAULT_PATH
                    NO_CMAKE_FIND_ROOT_PATH
                )
                message(DEBUG "configure_static_linking(${LIBRARY_NAME}): ${LIB_PATH}_ABSOLUTE_PATH = ${${LIB_PATH}_ABSOLUTE_PATH}")
                if(NOT EXISTS "${${LIB_PATH}_ABSOLUTE_PATH}")
                    find_static_library_in_pkg_config_path("${LIB_PATH}" ${LIB_PATH}_ABSOLUTE_PATH ${${LIBRARY_NAME}_REAL_LIBRARY_DIRS})
                    if(NOT EXISTS "${${LIB_PATH}_ABSOLUTE_PATH}")
                        message(DEBUG "configure_static_linking(${LIBRARY_NAME}): ${${LIB_PATH}_ABSOLUTE_PATH} file does not exist after search")
                        continue()
                    endif()
                endif()
                get_filename_component(${LIB_PATH}_ABSOLUTE_PATH_REALPATH "${${LIB_PATH}_ABSOLUTE_PATH}" REALPATH)
                set(${LIB_PATH}_ABSOLUTE_PATH "${${LIB_PATH}_ABSOLUTE_PATH_REALPATH}")
                message(STATUS "configure_static_linking(${LIBRARY_NAME}): replaced '${LIB_PATH}' with '${${LIB_PATH}_ABSOLUTE_PATH}'")
                set(LIB_PATH "${${LIB_PATH}_ABSOLUTE_PATH}")
            endif()
        endif()
        if(EXISTS "${LIB_PATH}")
            get_filename_component(LIB_PATH_REALPATH "${LIB_PATH}" REALPATH)
            set(LIB_PATH "${LIB_PATH_REALPATH}")
        endif()
        if(STATIC_LINKING)
            replace_shared_with_static("${LIB_PATH}" RESOLVED_LIB ${${LIBRARY_NAME}_REAL_LIBRARY_DIRS})
        else()
            if(MINGW)
                replace_dll_a_with_dll("${LIB_PATH}" RESOLVED_LIB)
            else()
                set(RESOLVED_LIB ${LIB_PATH})
            endif()
        endif()
        if(EXISTS "${RESOLVED_LIB}")
            get_filename_component(RESOLVED_LIB_REALPATH "${RESOLVED_LIB}" REALPATH)
            set(RESOLVED_LIB "${RESOLVED_LIB_REALPATH}")
        endif()
        ffmpegkit_cache_link_resolution("${_cache_namespace}" "${_original_lib_path}" "${RESOLVED_LIB}")
        if(NOT "${_original_lib_path}" STREQUAL "${LIB_PATH}")
            ffmpegkit_cache_link_resolution("${_cache_namespace}" "${LIB_PATH}" "${RESOLVED_LIB}")
        endif()
        list(APPEND FIXED_LIBS "${RESOLVED_LIB}")
    endforeach()
    set_target_properties(PkgConfig::${LIBRARY_NAME} PROPERTIES INTERFACE_LINK_LIBRARIES "${FIXED_LIBS}")
    list(APPEND BUNDLE_LIBRARIES ${FIXED_LIBS})
    list(REMOVE_DUPLICATES BUNDLE_LIBRARIES)
    set(BUNDLE_LIBRARIES "${BUNDLE_LIBRARIES}" PARENT_SCOPE)
endfunction()

function(configure_shared_linking LIBRARY_NAME SHARED_LINKING)
    get_target_property(${LIBRARY_NAME}_LIBS PkgConfig::${LIBRARY_NAME} INTERFACE_LINK_LIBRARIES)
    if(NOT ${LIBRARY_NAME}_LIBS OR ${LIBRARY_NAME}_LIBS MATCHES "-NOTFOUND$")
        set(${LIBRARY_NAME}_LIBS "${${LIBRARY_NAME}_LINK_LIBRARIES}")
    endif()
    if(NOT ${LIBRARY_NAME}_LIBS_LIST)
        if(EXISTS "${${LIBRARY_NAME}_LIBRARY}")
            message(STATUS "configure_shared_linking(${LIBRARY_NAME}): ${LIBRARY_NAME} found at ${${LIBRARY_NAME}_LIBRARY}")
            set(${LIBRARY_NAME}_LIBS_LIST "${${LIBRARY_NAME}_LIBRARY}")
        elseif(EXISTS "${${LIBRARY_NAME}_LIBS}")
            message(STATUS "configure_shared_linking(${LIBRARY_NAME}): ${LIBRARY_NAME} found at ${${LIBRARY_NAME}_LIBS}")
            set(${LIBRARY_NAME}_LIBS_LIST "${${LIBRARY_NAME}_LIBS}")
        elseif(EXISTS "${${LIBRARY_NAME}_LIBRARIES}")
            message(STATUS "configure_shared_linking(${LIBRARY_NAME}): ${LIBRARY_NAME} found at ${${LIBRARY_NAME}_LIBRARIES}")
            set(${LIBRARY_NAME}_LIBS_LIST "${${LIBRARY_NAME}_LIBRARIES}")
        else()
            message(WARNING "configure_shared_linking(${LIBRARY_NAME}): ${LIBRARY_NAME}_LIBS_LIST is empty")
            return()
        endif()
    endif()
    set(FIXED_LIBS "")
    set(_cache_namespace "SHARED_${SHARED_LINKING}")
    message(DEBUG "configure_shared_linking(${LIBRARY_NAME}): ${LIBRARY_NAME}_LIBS_LIST = ${${LIBRARY_NAME}_LIBS_LIST}")
    foreach(LIB_PATH IN LISTS ${LIBRARY_NAME}_LIBS_LIST)
        message(DEBUG "configure_shared_linking(${LIBRARY_NAME}): checking entry '${LIB_PATH}'")
        if(LIB_PATH MATCHES "-NOTFOUND$" OR LIB_PATH STREQUAL "")
            message(WARNING "configure_shared_linking(${LIBRARY_NAME}): skipping unresolved entry '${LIB_PATH}'")
            continue()
        endif()
        set(_original_lib_path "${LIB_PATH}")
        ffmpegkit_get_cached_link_resolution("${_cache_namespace}" "${_original_lib_path}" RESOLVED_LIB _cache_hit)
        if(_cache_hit)
            message(DEBUG "configure_shared_linking(${LIBRARY_NAME}): cache hit '${_original_lib_path}' -> '${RESOLVED_LIB}'")
            list(APPEND FIXED_LIBS "${RESOLVED_LIB}")
            continue()
        endif()
        if(SHARED_LINKING)
            replace_static_with_shared("${LIB_PATH}" RESOLVED_LIB)
        else()
            if(MINGW)
                replace_dll_a_with_dll("${LIB_PATH}" RESOLVED_LIB)
            else()
                set(RESOLVED_LIB ${LIB_PATH})
            endif()
        endif()
        ffmpegkit_cache_link_resolution("${_cache_namespace}" "${_original_lib_path}" "${RESOLVED_LIB}")
        list(APPEND FIXED_LIBS "${RESOLVED_LIB}")
    endforeach()
    set_target_properties(PkgConfig::${LIBRARY_NAME} PROPERTIES INTERFACE_LINK_LIBRARIES "${FIXED_LIBS}")
    list(APPEND BUNDLE_LIBRARIES ${FIXED_LIBS})
    list(REMOVE_DUPLICATES BUNDLE_LIBRARIES)
    set(BUNDLE_LIBRARIES "${BUNDLE_LIBRARIES}" PARENT_SCOPE)
endfunction()
