#!/usr/bin/env bash

# Run from ffmpeg-kit-builders project root
TARGET_DIR="FFmpegKit/src"

if [ ! -d "$TARGET_DIR" ]; then
    echo "Error: $TARGET_DIR not found"
    exit 1
fi
echo "------------------------------------------------------------"
echo "Report generated by $(realpath "${BASH_SOURCE[0]}")"
echo "------------------------------------------------------------"
echo ""
EXCLUDE_FILES=(
    "FFmpegKit/src/ffmpeg_tls.h"
    "FFmpegKit/src/FFmpegKitConfig.cpp"
)

# Robust compile commands check
P_FLAG=""
if [ -f "compile_commands.json" ]; then
    P_FLAG="-p ."
elif [ -f "$TARGET_DIR/compile_commands.json" ]; then
    P_FLAG="-p $TARGET_DIR"
fi

mapfile -t FILE_LIST < <(grep -rl "FFMPEG_THREAD_LOCAL" "$TARGET_DIR")

for file_rel in "${FILE_LIST[@]}"; do
    file_rel=$(echo "$file_rel" | tr -d '\r')
    
    # Skip excluded files
    skip=0
    for ex in "${EXCLUDE_FILES[@]}"; do [[ "$file_rel" == "$ex" ]] && skip=1; done
    [[ $skip -eq 1 ]] && continue

    full_path="$(pwd)/$file_rel"
    
    # Extract variable names
    mapfile -t VAR_LINES < <(grep -n "FFMPEG_THREAD_LOCAL" "$full_path")

    for var_line in "${VAR_LINES[@]}"; do
        if [[ "$var_line" == *"(*"* ]]; then
            name=$(echo "$var_line" | gsed -E 's/.*(\(\*([a-zA-Z0-9_]+)\)).*/\2/')
        else
            name=$(echo "$var_line" | gsed -E 's/.*FFMPEG_THREAD_LOCAL//; s/[[;=].*//; s/.*[[:space:]*]([a-zA-Z0-9_]+)[[:space:]]*$/\1/' | xargs)
        fi

        [[ -z "$name" || "$var_line" == *"#define"* ]] && continue

        echo "------------------------------------------------------------"
        echo "TLS VARIABLE DEFINITION: $full_path:$var_line"
        echo "VARIABLE: $name (Defined in: $full_path)"
        echo "------------------------------------------------------------"

        QUERY="match declRefExpr(to(varDecl(hasName('$name')))).bind('usage')"
        
        # 1. Run clang-query
        # 2. Filter for lines that actually look like source locations (path:line:col)
        # 3. Use gsed to extract only the path:line portion
        clang-query $P_FLAG "$full_path" \
            -c "$QUERY" \
            --extra-arg="-DFFMPEG_THREAD_LOCAL=__thread" \
            --extra-arg="-I$TARGET_DIR" \
            2>/dev/null | \
            grep -E "^/.*:[0-9]+:[0-9]+" | \
            gsed -i -E 's/^(.+:[0-9]+):[0-9]+.*/\1/' | \
            while read -r loc; do
                
                [[ -z "$loc" ]] && continue
                
                f_path=$(echo "$loc" | cut -d: -f1)
                l_num=$(echo "$loc" | cut -d: -f2)
                
                # Check if file exists and line number is valid
                if [[ -f "$f_path" && "$l_num" =~ ^[0-9]+$ ]]; then
                    line_content=$(gsed -i "${l_num}q;d" "$f_path" | xargs)
                    
                    # Output match if it's not the declaration line
                    if [[ ! "$line_content" == *"FFMPEG_THREAD_LOCAL"* ]]; then
                        echo "$f_path:$l_num:$line_content"
                    fi
                fi
            done
        
        echo ""
    done
done