#!/usr/bin/env bash

if (( BASH_VERSINFO[0] < 5 )); then
    for bash in /opt/homebrew/bin/bash /usr/local/bin/bash; do
        if [[ -x "$bash" ]]; then
            exec "$bash" "$0" "$@"
        fi
    done

    echo "GNU Bash 5+ is required." >&2
    exit 1
fi

set -euo pipefail

INPUT_LIST="${1:?input libs list required}"
MAP_FILE="${2:?map output path required}"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# Generate an exact old->new map for every unprefixed Mach-O LZMA symbol.
#
# Important:
#   - Do NOT strip dotted suffixes.
#   - Mach-O local/static symbols may look like:
#       _lzma_lzma_preset.depths
#       _lzma_check_size.check_sizes
#       _lzma_sha256_init.s
#   - llvm-objcopy --redefine-syms needs exact symbol names.
while IFS= read -r item || [ -n "$item" ]; do
  [[ "$item" == *.a && -f "$item" ]] || continue

  {
    nm -u "$item" 2>/dev/null || true
    nm -m "$item" 2>/dev/null || true
    nm "$item" 2>/dev/null || true
  }
done < "$INPUT_LIST" |
awk '
  {
    sym = $NF

    # Match exact symbol tokens beginning with _lzma_.
    # Allow "." for function-local/static Mach-O symbols.
    if (sym ~ /^_lzma_[A-Za-z0-9_.]+$/) {
      print sym
    }
  }
' |
sort -u > "$TMP"

{
  echo "# Generated by generate-lzma-map-from-libs.sh"
  echo "# old_symbol new_symbol"

  while IFS= read -r sym; do
    [ -n "$sym" ] || continue

    # _lzma_code -> _ffmpegkit_lzma_code
    # _lzma_lzma_preset.depths -> _ffmpegkit_lzma_lzma_preset.depths
    printf "%s %s\n" "$sym" "_ffmpegkit${sym}"
  done < "$TMP"
} > "$MAP_FILE"

echo "Generated $(grep -vc '^[[:space:]]*#' "$MAP_FILE" || true) LZMA symbol rewrites"