services:
  ffmpeg-kit-builders:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      tags:
        - ghcr.io/akashskypatel/ffmpeg-kit-builders-dev:latest
    image: ghcr.io/akashskypatel/ffmpeg-kit-builders-dev:latest
    container_name: ffmpeg-kit-builders-dev
    working_dir: /workspaces/ffmpeg-kit-builders
    command: sleep infinity
    stdin_open: true
    tty: true
    user: vscode
    environment:
      RUSTUP_HOME: /usr/local/rustup
      CARGO_HOME: /usr/local/cargo
      ANDROID_HOME: /usr/local/android-sdk
      ANDROID_SDK_ROOT: /usr/local/android-sdk
      ANDROID_NDK_VERSION: 29.0.14206865
      ANDROID_NDK_ROOT: /usr/local/android-sdk/ndk/29.0.14206865
      ANDROID_NDK_HOME: /usr/local/android-sdk/ndk/29.0.14206865
      NDK_HOME: /usr/local/android-sdk/ndk/29.0.14206865
    volumes:
      - ..:/workspaces/ffmpeg-kit-builders:cached
