#!/bin/bash

#
# 1. library name
# 2. source type 1/2/3
#

get_library_source() {
  case $1 in
  chromaprint)
    SOURCE_REPO_URL="https://github.com/arthenica/chromaprint"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  cpu-features)
    SOURCE_REPO_URL="https://github.com/arthenica/cpu_features"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  expat)
    SOURCE_REPO_URL="https://github.com/arthenica/libexpat"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  jpeg)
    SOURCE_REPO_URL="https://github.com/arthenica/libjpeg-turbo"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  kvazaar)
    SOURCE_REPO_URL="https://github.com/arthenica/kvazaar"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libaom)
    SOURCE_REPO_URL="https://github.com/arthenica/libaom"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libsndfile)
    SOURCE_REPO_URL="https://github.com/arthenica/libsndfile"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libuuid)
    SOURCE_REPO_URL="https://github.com/arthenica/libuuid"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  openh264)
    SOURCE_REPO_URL="https://github.com/arthenica/openh264"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  openssl)
    SOURCE_REPO_URL="https://github.com/arthenica/openssl"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  opus)
    SOURCE_REPO_URL="https://github.com/arthenica/opus"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  sdl)
    SOURCE_REPO_URL="https://github.com/arthenica/SDL"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  shine)
    SOURCE_REPO_URL="https://github.com/arthenica/shine"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  tiff)
    SOURCE_REPO_URL="https://github.com/arthenica/libtiff"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  xvidcore)
    SOURCE_REPO_URL="https://github.com/arthenica/xvidcore"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  amf-headers)
    SOURCE_REPO_URL="https://github.com/GPUOpen-LibrariesAndSDKs/AMF"
    SOURCE_ID="v1.5.0"
    SOURCE_TYPE="TAG"
    ;;
  aom)
    SOURCE_REPO_URL="https://github.com/libsdl-org/aom"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  aribb24)
    SOURCE_REPO_URL="https://github.com/nkoriyama/aribb24"
    SOURCE_ID="v1.0.3"
    SOURCE_TYPE="TAG"
    ;;
  audiotoolboxwrapper)
    SOURCE_REPO_URL="https://github.com/cynagenautes/AudioToolboxWrapper"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  avisynth)
    SOURCE_REPO_URL="https://github.com/AviSynth/AviSynthPlus"
    SOURCE_ID="v3.7.5"
    SOURCE_TYPE="TAG"
    ;;
  brotli)
    SOURCE_REPO_URL="https://github.com/google/brotli"
    SOURCE_ID="v1.2.0"
    SOURCE_TYPE="TAG"
    ;;
  bzip2)
    SOURCE_REPO_URL="https://github.com/libarchive/bzip2"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  config)
    SOURCE_REPO_URL="https://github.com/arthenica/gnu-config"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  cpuinfo)
    SOURCE_REPO_URL="https://github.com/pytorch/cpuinfo"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  curl)
    SOURCE_REPO_URL="https://github.com/curl/curl"
    SOURCE_ID="curl-8_17_0"
    SOURCE_TYPE="TAG"
    ;;
  dav1d)
    SOURCE_REPO_URL="https://github.com/videolan/dav1d"
    SOURCE_ID="0.1.0"
    SOURCE_TYPE="TAG"
    ;;
  davs2)
    SOURCE_REPO_URL="https://github.com/pkuvcl/davs2"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  decklink-headers)
    SOURCE_REPO_URL="https://gitlab.com/m-ab-s/decklink-headers/-/archive/47d84f8d272ca6872b5440eae57609e36014f3b6/decklink-headers-47d84f8d272ca6872b5440eae57609e36014f3b6.zip"
    SOURCE_ID="47d84f8d272ca6872b5440eae57609e36014f3b6"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  dlfcn-win32)
    SOURCE_REPO_URL="https://github.com/dlfcn-win32/dlfcn-win32"
    SOURCE_ID="v1.4.2"
    SOURCE_TYPE="TAG"
    ;;
  dovi_tool)
    SOURCE_REPO_URL="https://github.com/quietvoid/dovi_tool"
    SOURCE_ID="2.3.1"
    SOURCE_TYPE="TAG"
    ;;
  dovi_tool_bin)
    SOURCE_REPO_URL="https://github.com/quietvoid/dovi_tool/releases/download/2.3.1/dovi_tool-2.3.1-x86_66-pc-windows-msvc.zip"
    SOURCE_ID="2.3.1"
    SOURCE_TYPE="TAG"
    ;;
  fdk-aac)
    SOURCE_REPO_URL="https://github.com/mstorsjo/fdk-aac"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  ffmpeg)
    SOURCE_REPO_URL="https://github.com/FFmpeg/FFmpeg"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  fftw)
    SOURCE_REPO_URL="http://fftw.org/fftw-3.3.10.tar.gz"
    SOURCE_ID="3.3.10"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  flac)
    SOURCE_REPO_URL="https://github.com/xiph/flac"
    SOURCE_ID="1.5.0"
    SOURCE_TYPE="TAG"
    ;;
  flite)
    SOURCE_REPO_URL="https://github.com/festvox/flite"
    SOURCE_ID="v2.2"
    SOURCE_TYPE="TAG"
    ;;
  fontconfig)
    SOURCE_REPO_URL="https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/main/fontconfig-main.zip"
    SOURCE_ID="master"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  frei0r)
    SOURCE_REPO_URL="https://github.com/dyne/frei0r/archive/refs/tags/v2.3.3.tar.gz"
    SOURCE_ID="v2.5.0"
    SOURCE_TYPE="TAG"
    ;;
  freetype)
    SOURCE_REPO_URL="https://github.com/freetype/freetype"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  fribidi)
    SOURCE_REPO_URL="https://github.com/fribidi/fribidi"
    SOURCE_ID="v1.0.16"
    SOURCE_TYPE="TAG"
    ;;
  gettext)
    SOURCE_REPO_URL="https://ftp.gnu.org/pub/gnu/gettext/gettext-0.26.tar.gz"
    SOURCE_ID="0.26"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  glfw)
    SOURCE_REPO_URL="https://github.com/glfw/glfw"
    SOURCE_ID="3.4"
    SOURCE_TYPE="TAG"
    ;;
  giflib)
    SOURCE_REPO_URL="https://sourceforge.net/projects/giflib/files/giflib-5.1.4.tar.gz"
    SOURCE_ID="5.1.4"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  glew)
    SOURCE_REPO_URL="https://sourceforge.net/projects/glew/files/glew/2.2.0/glew-2.2.0.tgz"
    SOURCE_ID="2.2.0"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  glib)
    SOURCE_REPO_URL="https://github.com/GNOME/glib"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  gmp)
    SOURCE_REPO_URL="https://ftp.gnu.org/pub/gnu/gmp/gmp-6.3.0.tar.xz"
    SOURCE_ID="6.3.0"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  gnutls)
    SOURCE_REPO_URL="https://www.gnupg.org/ftp/gcrypt/gnutls/v3.8/gnutls-3.8.9.tar.xz"
    SOURCE_ID="3.8.9"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  gpac)
    SOURCE_REPO_URL="https://github.com/gpac/gpac"
    SOURCE_ID="v2.4.0"
    SOURCE_TYPE="TAG"
    ;;
  harfbuzz)
    SOURCE_REPO_URL="https://github.com/harfbuzz/harfbuzz"
    SOURCE_ID="12.2.0"
    SOURCE_TYPE="TAG"
    ;;
  l-smash)
    SOURCE_REPO_URL="https://github.com/l-smash/l-smash"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  l-smash-works)
    SOURCE_REPO_URL="https://github.com/VFR-maniac/L-SMASH-Works"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  lame)
    SOURCE_REPO_URL="https://cytranet.dl.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz"
    SOURCE_ID="3.100"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  lcms)
    SOURCE_REPO_URL="https://github.com/ImageMagick/lcms"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  lensfun)
    SOURCE_REPO_URL="https://github.com/lensfun/lensfun"
    SOURCE_ID="v0.3.4"
    SOURCE_TYPE="TAG"
    ;;
  leptonica)
    SOURCE_REPO_URL="https://github.com/DanBloomberg/leptonica"
    SOURCE_ID="1.86.0"
    SOURCE_TYPE="TAG"
    ;;
  libaribcaption)
    SOURCE_REPO_URL="https://github.com/xqq/libaribcaption"
    SOURCE_ID="v1.1.1"
    SOURCE_TYPE="TAG"
    ;;
  libarchive)
    SOURCE_REPO_URL="https://github.com/libarchive/libarchive/releases/download/v3.8.1/libarchive-3.8.1.tar.gz"
    SOURCE_ID="v3.8.2"
    SOURCE_TYPE="TAG"
    ;;
  libass)
    SOURCE_REPO_URL="https://github.com/libass/libass"
    SOURCE_ID="0.17.4"
    SOURCE_TYPE="TAG"
    ;;
  libbluray)
    SOURCE_REPO_URL="https://code.videolan.org/videolan/libbluray/-/archive/master/libbluray-master.zip"
    SOURCE_ID="master"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  libbs2b)
    SOURCE_REPO_URL="https://downloads.sourceforge.net/project/bs2b/libbs2b/3.1.0/libbs2b-3.1.0.tar.gz"
    SOURCE_ID="3.1.0"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  libcaca)
    SOURCE_REPO_URL="https://github.com/cacalabs/libcaca"
    SOURCE_ID="v0.99.beta20"
    SOURCE_TYPE="TAG"
    ;;
  libdvbpsi)
    SOURCE_REPO_URL="https://github.com/mkrufky/libdvbpsi"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libdvbtee)
    SOURCE_REPO_URL="https://github.com/mkrufky/libdvbtee"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libdvdcss)
    SOURCE_REPO_URL="https://download.videolan.org/pub/videolan/libdvdcss/1.2.13/libdvdcss-1.2.13.tar.bz2"
    SOURCE_ID="1.2.13"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  libdvdnav)
    SOURCE_REPO_URL="http://dvdnav.mplayerhq.hu/releases/libdvdnav-4.2.1.tar.xz"
    SOURCE_ID="4.2.1"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  libdvdread)
    SOURCE_REPO_URL="http://dvdnav.mplayerhq.hu/releases/libdvdread-4.9.9.tar.xz"
    SOURCE_ID="4.9.9"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  libffi)
    SOURCE_REPO_URL="https://github.com/libffi/libffi"
    SOURCE_ID="v3.5.2"
    SOURCE_TYPE="TAG"
    ;;
  libgme)
    SOURCE_REPO_URL="https://bitbucket.org/mpyne/game-music-emu/downloads/game-music-emu-0.6.3.tar.xz"
    SOURCE_ID="0.6.3"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  libiconv)
    SOURCE_REPO_URL="https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz"
    SOURCE_ID="1.18"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  libidn2)
    SOURCE_REPO_URL="https://ftp.gnu.org/gnu/libidn/libidn2-2.3.8.tar.gz"
    SOURCE_ID="2.3.8"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  libilbc)
    SOURCE_REPO_URL="https://github.com/TimothyGu/libilbc"
    SOURCE_ID="v3.0.4"
    SOURCE_TYPE="TAG"
    ;;
  libjpeg-turbo)
    SOURCE_REPO_URL="https://github.com/libjpeg-turbo/libjpeg-turbo"
    SOURCE_ID="3.1.2"
    SOURCE_TYPE="TAG"
    ;;
  libmodplug)
    SOURCE_REPO_URL="https://github.com/Konstanty/libmodplug"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libmysofa)
    SOURCE_REPO_URL="https://github.com/hoene/libmysofa"
    SOURCE_ID="v1.3.2"
    SOURCE_TYPE="TAG"
    ;;
  libMXF)
    SOURCE_REPO_URL="https://sourceforge.net/projects/ingex/files/1.0.0/libMXF/libMXF-src-1.0.0.tgz"
    SOURCE_ID="1.0.0"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  libogg)
    SOURCE_REPO_URL="https://github.com/xiph/ogg"
    SOURCE_ID="v1.3.6"
    SOURCE_TYPE="TAG"
    ;;
  libopencore)
    SOURCE_REPO_URL="https://sourceforge.net/projects/opencore-amr/files/opencore-amr/opencore-amr-0.1.6.tar.gz"
    SOURCE_ID="0.1.6"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  libopenh264)
    SOURCE_REPO_URL="https://github.com/cisco/openh264"
    SOURCE_ID="v2.6.0"
    SOURCE_TYPE="TAG"
    ;;
  libopenjpeg)
    SOURCE_REPO_URL="https://github.com/uclouvain/openjpeg"
    SOURCE_ID="v2.5.4"
    SOURCE_TYPE="TAG"
    ;;
  libopus)
    SOURCE_REPO_URL="https://github.com/xiph/opus"
    SOURCE_ID="v1.5.2"
    SOURCE_TYPE="TAG"
    ;;
  libplacebo)
    SOURCE_REPO_URL="https://github.com/haasn/libplacebo"
    SOURCE_ID="v7.351.0"
    SOURCE_TYPE="TAG"
    ;;
  libpng)
    SOURCE_REPO_URL="https://github.com/glennrp/libpng"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libproxy)
    SOURCE_REPO_URL="https://github.com/libproxy/libproxy"
    SOURCE_ID="0.5.11"
    SOURCE_TYPE="TAG"
    ;;
  libpsl)
    SOURCE_REPO_URL="https://github.com/rockdaboot/libpsl/releases/download/0.21.5/libpsl-0.21.5.tar.gz"
    SOURCE_ID="0.21.5"
    SOURCE_TYPE="TAG"
    ;;
  librtmfp)
    SOURCE_REPO_URL="https://github.com/MonaSolutions/librtmfp"
    SOURCE_ID="v2.14.3"
    SOURCE_TYPE="TAG"
    ;;
  libsamplerate)
    SOURCE_REPO_URL="https://github.com/erikd/libsamplerate"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libssh2)
    SOURCE_REPO_URL="https://github.com/libssh2/libssh2/releases/download/libssh2-1.11.1/libssh2-1.11.1.tar.gz"
    SOURCE_ID="libssh2-1.11.1"
    SOURCE_TYPE="TAG"
    ;;
  libtheora)
    SOURCE_REPO_URL="https://github.com/xiph/theora"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libtiff)
    SOURCE_REPO_URL="https://github.com/libsdl-org/libtiff"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libunistring)
    SOURCE_REPO_URL="https://ftp.gnu.org/gnu/libunistring/libunistring-1.4.1.tar.gz"
    SOURCE_ID="1.4.1"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  libunwind)
    SOURCE_REPO_URL="https://github.com/libunwind/libunwind"
    SOURCE_ID="v1.8.3"
    SOURCE_TYPE="TAG"
    ;;
  libvidstab)
    SOURCE_REPO_URL="https://github.com/georgmartius/vid"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libvorbis)
    SOURCE_REPO_URL="https://github.com/xiph/vorbis"
    SOURCE_ID="v1.3.7"
    SOURCE_TYPE="TAG"
    ;;
  libvpl)
    SOURCE_REPO_URL="https://github.com/intel/libvpl"
    SOURCE_ID="v2.15.0"
    SOURCE_TYPE="TAG"
    ;;
  libvpx)
    SOURCE_REPO_URL="https://github.com/webmproject/libvpx"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libvvdec)
    SOURCE_REPO_URL="https://github.com/fraunhoferhhi/vvdec"
    SOURCE_ID="v3.0.0"
    SOURCE_TYPE="TAG"
    ;;
  libvvenc)
    SOURCE_REPO_URL="https://github.com/fraunhoferhhi/vvenc"
    SOURCE_ID="v1.13.1"
    SOURCE_TYPE="TAG"
    ;;
  libwebp)
    SOURCE_REPO_URL="https://github.com/webmproject/libwebp"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libxml2)
    SOURCE_REPO_URL="https://github.com/GNOME/libxml2"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  libxvid)
    SOURCE_REPO_URL="https://downloads.xvid.com/downloads/xvidcore-1.3.7.tar.gz"
    SOURCE_ID="1.3.7"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  lua)
    SOURCE_REPO_URL="https://www.lua.org/ftp/lua-5.3.3.tar.gz"
    SOURCE_ID="5.3.3"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  lz4)
    SOURCE_REPO_URL="https://github.com/lz4/lz4"
    SOURCE_ID="v1.10.0"
    SOURCE_TYPE="TAG"
    ;;
  mfx-dispatch)
    SOURCE_REPO_URL="https://github.com/lu-zero/mfx_dispatch"
    SOURCE_ID="1.35.1"
    SOURCE_TYPE="TAG"
    ;;
  mingw-std-threads)
    SOURCE_REPO_URL="https://github.com/meganz/mingw-std-threads"
    SOURCE_ID="1.0.0"
    SOURCE_TYPE="TAG"
    ;;
  mplayer)
    SOURCE_REPO_URL="https://sourceforge.net/projects/mplayer-edl/files/mplayer-export-snapshot.2014-05-19.tar.bz2"
    SOURCE_ID="2014-05-19"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  mplayer-ffmpeg)
    SOURCE_REPO_URL="https://github.com/FFmpeg/FFmpeg"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  mpg123)
    SOURCE_REPO_URL="https://mpg123.org/download/mpg123-1.33.3.tar.bz2"
    SOURCE_ID="1.33.3"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  nettle)
    SOURCE_REPO_URL="https://ftp.gnu.org/gnu/nettle/nettle-3.10.2.tar.gz"
    SOURCE_ID="3.10.2"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  nghttp2)
    SOURCE_REPO_URL="https://github.com/nghttp2/nghttp2/releases/download/v1.67.1/nghttp2-1.67.1.tar.gz"
    SOURCE_ID="v1.68.0"
    SOURCE_TYPE="TAG"
    ;;
  nv-codec-headers)
    SOURCE_REPO_URL="https://github.com/FFmpeg/nv-codec-headers"
    SOURCE_ID="n13.0.19.0"
    SOURCE_TYPE="TAG"
    ;;
  opencore-amr)
    SOURCE_REPO_URL="https://sourceforge.net/projects/opencore-amr/files/opencore-amr/opencore-amr-0.1.6.tar.gz"
    SOURCE_ID="0.1.6"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  openmpt)
    SOURCE_REPO_URL="https://github.com/OpenMPT/openmpt"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  openssl-1.0.2)
    SOURCE_REPO_URL="https://www.openssl.org/source/openssl-1.0.2p.tar.gz"
    SOURCE_ID="1.0.2p"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  openssl-1.1.1)
    SOURCE_REPO_URL="https://www.openssl.org/source/openssl-1.1.1.tar.gz"
    SOURCE_ID="1.1.1"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  opencv)
    SOURCE_REPO_URL="https://github.com/opencv/opencv/archive/3.4.5.zip"
    SOURCE_ID="4.12.0"
    SOURCE_TYPE="TAG"
    ;;
  qt)
    SOURCE_REPO_URL="http://pkgs.fedoraproject.org/repo/pkgs/qt/qt-everywhere-opensource-src-4.8.5.tar.gz/1864987bdbb2f58f8ae8b350dfdbe133/qt-everywhere-opensource-src-4.8.5.tar.gz"
    SOURCE_ID="4.8.5"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  rubberband)
    SOURCE_REPO_URL="https://github.com/breakfastquay/rubberband"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  sdl2)
    SOURCE_REPO_URL="https://www.libsdl.org/release/SDL2-2.32.10.tar.gz"
    SOURCE_ID="2.32.10"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  shaderc)
    SOURCE_REPO_URL="https://github.com/google/shaderc"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  snappy)
    SOURCE_REPO_URL="https://github.com/google/snappy"
    SOURCE_ID="1.2.2"
    SOURCE_TYPE="TAG"
    ;;
  soxr)
    SOURCE_REPO_URL="https://github.com/chirlu/soxr"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  speex)
    SOURCE_REPO_URL="https://github.com/xiph/speex"
    SOURCE_ID="Speex-1.2.1"
    SOURCE_TYPE="TAG"
    ;;
  speexdsp)
    SOURCE_REPO_URL="https://github.com/xiph/speexdsp"
    SOURCE_ID="SpeexDSP-1.2.1"
    SOURCE_TYPE="TAG"
    ;;
  spirv-cross)
    SOURCE_REPO_URL="https://github.com/KhronosGroup/SPIRV-Cross"
    SOURCE_ID="MoltenVK-1.1.5"
    SOURCE_TYPE="TAG"
    ;;
  srt)
    SOURCE_REPO_URL="https://github.com/Haivision/srt/archive/v1.5.4.tar.gz"
    SOURCE_ID="v1.5.4"
    SOURCE_TYPE="TAG"
    ;;
  svt-av1)
    SOURCE_REPO_URL="https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/master/SVT-AV1-master.zip"
    SOURCE_ID="master"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  svt-hevc)
    SOURCE_REPO_URL="https://github.com/OpenVisualCloud/SVT-HEVC"
    SOURCE_ID="v1.5.1"
    SOURCE_TYPE="TAG"
    ;;
  svt-vp9)
    SOURCE_REPO_URL="https://github.com/OpenVisualCloud/SVT-VP9"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  tensorflow)
    SOURCE_REPO_URL="https://storage.googleapis.com/tensorflow/versions/2.18.1/libtensorflow-cpu-windows-x86_64.zip"
    SOURCE_ID="2.18.1"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  tesseract)
    SOURCE_REPO_URL="httpsT://github.com/tesseract-ocr/tesseract"
    SOURCE_ID="master"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  transform360)
    SOURCE_REPO_URL="https://github.com/facebook/transform360"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  twolame)
    SOURCE_REPO_URL="https://github.com/njh/twolame"
    SOURCE_ID="0.4.0"
    SOURCE_TYPE="TAG"
    ;;
  vamp-plugin-sdk)
    SOURCE_REPO_URL="https://github.com/vamp-plugins/vamp-plugin-sdk"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  vlc)
    SOURCE_REPO_URL="https://github.com/videolan/vlc"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  vmaf)
    SOURCE_REPO_URL="https://github.com/Netflix/vmaf"
    SOURCE_ID="v3.0.0"
    SOURCE_TYPE="TAG"
    ;;
  vo-amrwbenc)
    SOURCE_REPO_URL="https://sourceforge.net/projects/opencore-amr/files/vo-amrwbenc/vo-amrwbenc-0.1.3.tar.gz"
    SOURCE_ID="0.1.3"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  vulkan-headers)
    SOURCE_REPO_URL="https://github.com/KhronosGroup/Vulkan-Headers"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  vulkan-shim-loader)
    SOURCE_REPO_URL="https://github.com/BtbN/Vulkan-Shim-Loader"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  x264)
    SOURCE_REPO_URL="https://github.com/mirror/x264"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  x265)
    SOURCE_REPO_URL="https://github.com/videolan/x265"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  xavs)
    SOURCE_REPO_URL="https://github.com/Distrotech/xavs"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  xavs2)
    SOURCE_REPO_URL="https://github.com/pkuvcl/xavs2"
    SOURCE_ID="master"
    SOURCE_TYPE="BRANCH"
    ;;
  xxhash)
    SOURCE_REPO_URL="https://github.com/Cyan4973/xxHash"
    SOURCE_ID="v0.8.3"
    SOURCE_TYPE="TAG"
    ;;
  xz)
    SOURCE_REPO_URL="https://sourceforge.net/projects/lzmautils/files/xz-5.8.1.tar.xz"
    SOURCE_ID="5.8.1"
    SOURCE_TYPE="DOWNLOAD"
    ;;
  zimg)
    SOURCE_REPO_URL="https://github.com/sekrit-twc/zimg"
    SOURCE_ID="release-3.0.6"
    SOURCE_TYPE="TAG"
    ;;
  zlib)
    SOURCE_REPO_URL="https://github.com/madler/zlib"
    SOURCE_ID="v1.3.1"
    SOURCE_TYPE="TAG"
    ;;
  zstd)
    SOURCE_REPO_URL="https://github.com/facebook/zstd"
    SOURCE_ID="v1.5.7"
    SOURCE_TYPE="TAG"
    ;;
  zvbi)
    SOURCE_REPO_URL="https://github.com/zapping-vbi/zvbi"
    SOURCE_ID="v0.2.44"
    SOURCE_TYPE="TAG"
    ;;
  esac

  case $2 in
  1)
    echo "${SOURCE_REPO_URL}"
    ;;
  2)
    echo "${SOURCE_ID}"
    ;;
  3)
    echo "${SOURCE_TYPE}"
    ;;
  esac
}
