name: build_all_iphonesimulator

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build:
    name: iphonesimulator ${{ matrix.arch }}
    runs-on: macos-14
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        arch: [aarch64]
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare scripts
        shell: bash
        run: chmod +x runner.sh scripts/*.sh

      - name: Install Bash
        shell: bash
        run: |
          brew install 'bash' 'coreutils' 'ragel' 'curl' 'pkg-config' 'make' 'git' 'svn' 'gcc' 'autoconf' 'automake' 'yasm' 'cvs' 'flex' 'bison' 'ed' 'pax' 'unzip' 'wget' 'xz' 'nasm' 'gperf' 'autogen' 'bzip2' 'python3' 'bc' 'texinfo' 'glib' 'llvm' 'lld' 'pipx' 'autoconf-archive' 'bc' 'binutils' 'gpatch' 'libtool' 'gsed'
          echo "HOMEBREW_BASH=$(brew --prefix)/bin/bash" >> "$GITHUB_ENV"

      - name: Accept Xcode license
        shell: bash
        run: sudo xcodebuild -license accept

      - name: Build iphonesimulator dependencies
        shell: bash
        run: |
          set -euo pipefail

          platform="iphonesimulator"
          arch="${{ matrix.arch }}"
          WORKFLOW_BUILD_STEPS="$(sudo -E "$HOMEBREW_BASH" ./runner.sh --host="$platform" --arch="$arch" --enable-full --gpl -y --no-bundle --skip --print-all-steps | awk -F= '/^WORKFLOW_BUILD_STEPS=/{print $2}')"
          echo "WORKFLOW_BUILD_STEPS: $WORKFLOW_BUILD_STEPS"

          for build in $WORKFLOW_BUILD_STEPS; do
            echo "Running $build for ${platform}-${arch}"
            sudo -E "$HOMEBREW_BASH" ./runner.sh --host="$platform" --arch="$arch" --enable-full --gpl -y --no-bundle --skip --workflow --build-only="$build"
            sudo rm -rf "${GITHUB_WORKSPACE}/prebuilt/${platform}-${arch}/libraries"
          done

      - name: Upload failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-artifacts-${{ github.workflow }}-${{ github.job }}-${{ matrix.arch }}
          path: |
            build.log
            prebuilt
          if-no-files-found: ignore
