name: build_d3d12va

run-name: ${{ github.workflow }} ${{ inputs.platform || 'all' }}-${{ inputs.arch || 'all' }} ${{ inputs.orchestrator_run_id || github.run_id }}

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform to build
        type: choice
        default: all
        options:
          - all
          - linux
          - windows
          - android
          - ios
          - iphonesimulator
          - macos
          - apple
      arch:
        description: Architecture to build
        type: choice
        default: all
        options:
          - all
          - x86_64
          - aarch64
          - armv7a

permissions:
  contents: write
  packages: read
  actions: read

jobs:
  linux:
    name: Linux
    if: ${{ inputs.platform == 'all' || inputs.platform == 'linux' || inputs.platform == 'windows' || inputs.platform == 'android' }}
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ github.token }}
    container:
      image: ghcr.io/akashskypatel/ffmpeg-kit-builders-dev:latest
      credentials:
        username: akashskypatel
        password: ${{ secrets.GHCR_PAT || github.token }}
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare scripts
        shell: bash
        run: chmod +x runner.sh scripts/*.sh

      - name: Build Linux
        if: ${{ (inputs.platform == 'all' || inputs.platform == 'linux') && (inputs.arch == 'all' || inputs.arch == 'x86_64') }}
        shell: bash
        run: sudo -E ./runner.sh --host=linux --arch=x86_64 -y --enable-full --enable-gpl --skip --workflow --build-only=${{ github.workflow }}

      - name: Build Windows
        if: ${{ (inputs.platform == 'all' || inputs.platform == 'windows') && (inputs.arch == 'all' || inputs.arch == 'x86_64') }}
        shell: bash
        run: sudo -E ./runner.sh --host=windows --arch=x86_64 -y --enable-full --enable-gpl --skip --workflow --build-only=${{ github.workflow }}

      - name: Build Android x86_64
        if: ${{ (inputs.platform == 'all' || inputs.platform == 'android') && (inputs.arch == 'all' || inputs.arch == 'x86_64') }}
        shell: bash
        run: sudo -E ./runner.sh --host=android --arch=x86_64 -y --enable-full --enable-gpl --skip --workflow --build-only=${{ github.workflow }}

      - name: Build Android arm64
        if: ${{ (inputs.platform == 'all' || inputs.platform == 'android') && (inputs.arch == 'all' || inputs.arch == 'aarch64') }}
        shell: bash
        run: sudo -E ./runner.sh --host=android --arch=aarch64 -y --enable-full --enable-gpl --skip --workflow --build-only=${{ github.workflow }}

      - name: Build Android armv7a
        if: ${{ (inputs.platform == 'all' || inputs.platform == 'android') && (inputs.arch == 'all' || inputs.arch == 'armv7a') }}
        shell: bash
        run: sudo -E ./runner.sh --host=android --arch=armv7a -y --enable-full --enable-gpl --skip --workflow --build-only=${{ github.workflow }}

  macos:
    name: macOS
    if: ${{ inputs.platform == 'all' || inputs.platform == 'apple' || inputs.platform == 'ios' || inputs.platform == 'iphonesimulator' || inputs.platform == 'macos' }}
    runs-on: macos-14
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare scripts
        shell: bash
        run: chmod +x runner.sh scripts/*.sh

      - name: Install Bash
        shell: bash
        run: |
          brew install 'bash' 'coreutils' 'ragel' 'curl' 'pkg-config' 'make' 'git' 'svn' 'gcc' 'autoconf' 'automake' 'yasm' 'cvs' 'flex' 'bison' 'ed' 'pax' 'unzip' 'wget' 'xz' 'nasm' 'gperf' 'autogen' 'bzip2' 'python3' 'bc' 'texinfo' 'glib' 'llvm' 'lld' 'pipx' 'autoconf-archive' 'bc' 'binutils' 'gpatch' 'libtool' 'gsed'
          echo "HOMEBREW_BASH=$(brew --prefix)/bin/bash" >> "$GITHUB_ENV"

      - name: Accept Xcode license
        shell: bash
        run: sudo xcodebuild -license accept

      - name: Build iOS
        if: ${{ (inputs.platform == 'all' || inputs.platform == 'apple' || inputs.platform == 'ios') && (inputs.arch == 'all' || inputs.arch == 'aarch64') }}
        shell: bash
        run: sudo "$HOMEBREW_BASH" ./runner.sh --host=ios --arch=aarch64 -y --enable-full --enable-gpl --skip --workflow --build-only=${{ github.workflow }}

      - name: Build iPhone Simulator
        if: ${{ (inputs.platform == 'all' || inputs.platform == 'apple' || inputs.platform == 'iphonesimulator') && (inputs.arch == 'all' || inputs.arch == 'aarch64') }}
        shell: bash
        run: sudo "$HOMEBREW_BASH" ./runner.sh --host=iphonesimulator --arch=aarch64 -y --enable-full --enable-gpl --skip --workflow --build-only=${{ github.workflow }}

      - name: Build macOS x86_64
        if: ${{ (inputs.platform == 'all' || inputs.platform == 'apple' || inputs.platform == 'macos') && (inputs.arch == 'all' || inputs.arch == 'x86_64') }}
        shell: bash
        run: sudo "$HOMEBREW_BASH" ./runner.sh --host=macos --arch=x86_64 -y --enable-full --enable-gpl --skip --workflow --build-only=${{ github.workflow }}

      - name: Build macOS arm64
        if: ${{ (inputs.platform == 'all' || inputs.platform == 'apple' || inputs.platform == 'macos') && (inputs.arch == 'all' || inputs.arch == 'aarch64') }}
        shell: bash
        run: sudo "$HOMEBREW_BASH" ./runner.sh --host=macos --arch=aarch64 -y --enable-full --enable-gpl --skip --workflow --build-only=${{ github.workflow }}
